### ISSUE TITLE
CVE-2023-29406 | needs Vulnerability fix

### ISSUE THREAD

**Issue by anil-kumar-acquia** [grpc-ecosystem/grpc-health-probe#150]
In current go version of grpc_health_probe there is CVE-2023-29406 Vulnerability which can fix with go version update to v1.20.6

**Comment by ahmetb** [comment]
This should not be applicable to grpc_health_probe. You can ignore it.

**Comment by anil-kumar-acquia** [comment]
Here is the impact path:

<img width="555" alt="Screenshot 2023-07-27 at 11 07 08 AM" src="https://github.com/grpc-ecosystem/grpc-health-probe/assets/69515310/8522256f-327a-46b6-9ed8-37b202512f1b">

<div class="table-wrap">


ID | Severity | Watch Name | Type | Component | Created | Policies
-- | -- | -- | -- | -- | -- | --
CVE-2023-29406 | Medium | vuln-dev | Security | github.com/golang/go:1.20.5 | 21-07-23 17:46:29 +0530 | DevScan


</div>
<p>&nbsp;</p>

**Comment by 87utierrez** [comment]
Hi @ahmetb 
I have cloned the repo to my local machine, I would like to fix the issue for GO 1.20.5 to 1.20.6 but I'm new DevOps and I'm a level 1 type. I was hoping that you could guide me on how I can execute a recompile of the code from a clone of this repo

**Comment by rujutaghanekar** [comment]
Facing another related vulnerability CVE-2023-29409. Fix needs go version update from 1.20.5 to 1.20.7

<img width="643" alt="Screenshot 2023-08-18 at 1 55 04 PM" src="https://github.com/grpc-ecosystem/grpc-health-probe/assets/35961231/0146336d-4f43-4b5f-981e-333227135653">

**Comment by jimknochelmann** [comment]
@ahmetb I confirmed by building the image locally, there are no code changes required to clear out these CVEs (`grpc-health-probe` will be built using go 1.20.7 because the version is [set](https://github.com/grpc-ecosystem/grpc-health-probe/blob/master/Dockerfile#L1) to 1.20). Maybe you could just kick off a build to clear this up?

Even though these CVEs do not introduce any risk (they are not exploitable as you mentioned above), there is value in clearing up the noise in vulnerability reports.  Digging in to understand why this doesn't matter takes time for everyone using this tool. So, perhaps if it's just a button push to rebuild, maybe it's easier to push the button than to have every product using this tool create and track an assessment.

**Comment by ahmetb** [comment]
> So, perhaps if it's just a button push to rebuild, maybe it's easier to push the button than to have every product using this tool create and track an assessment.

Unfortunately, it's not a single push button to update `go.mod`, tag a release and push it. And this happens very frequently (50% of the issues in this repo are meaningless image scanner alerts people get from unrelated packages).

**Comment by jimknochelmann** [comment]
Hi @ahmetb, If you have time, can we explore a couple of these points? Maybe I (or some other interested party) can contribute a PR to help improve this process so it _will_ be just a button push.

> not a single push button to update go.mod

It looks like dependabot is already bumping version in `go.mod` without intervention ([example](https://github.com/grpc-ecosystem/grpc-health-probe/pull/151)). What else is required here? Maybe this could be part of the PR when people are requesting new builds?


> tag a release and push it

I was assuming that [this](https://github.com/grpc-ecosystem/grpc-health-probe/blob/master/.github/workflows/release.yml) was the code responsible for doing the release. Is this still used? What could be contributed in a PR to make this release process a single button push on your end?

> 50% of the issues in this repo are meaningless image scanner alerts people get from unrelated packages

Agreed, the issues detected by the scanners are pretty annoying because they often highlight packages that do not expose any real risk (they are not exploitable in any way). The goal would be to clean up the noise in the security report, not to improve the security posture. If the version is just bumped, nobody will open up a thread like this, and you'll never have to take time explaining why it doesn't matter. That's the real goal. For me, I've been pinged about 5 times about this grpc health probe, and I send the requester info about why it's not exploitable (which I 100% agree with)... But I'd rather if they just didn't ask me.

Anyway, just my 2 cents. If I can help with any improvements here, I'd like to contribute. Maybe we can just set up a monthly cron job or something?

**Comment by binalp7** [comment]
@ahmetb Is there any update on this?

**Comment by rujutaghanekar** [comment]
Facing another related vulnerability [CVE-2023-29406](https://www.cve.org/CVERecord?id=CVE-2023-29406)
<img width="626" alt="Screenshot 2023-10-03 at 2 37 07 PM" src="https://github.com/grpc-ecosystem/grpc-health-probe/assets/35961231/7414492f-a407-49f8-baf9-9286d00d30bf">
