### ISSUE TITLE
Provide binary releases for macOS and Windows as well as an official Linux container image

### ISSUE THREAD

**Issue by spkane** [grpc-ecosystem/grpc-health-probe#61]
In development it is often useful to use this tool for testing. It would be nice to have macOS and Windows binaries available from the releases page for download as well as a trusted container image available on Docker hub or GCR.

- A tool like [gox](https://github.com/mitchellh/gox) can be used to create the binaries pretty easily.
- And Github Actions can be setup pretty easily to handle building the container image when new code is merged.

**Comment by ahmetb** [comment]
Happy to provide more cross-platform binaries, however not sure why you need a container image.
That was discussed before in #32 and I am not convinced why this is needed.

**Comment by spkane** [comment]
I think it is mostly desired as a convenience, without the cross-platform binaries it is the only way to run `grpc_health_check` on those platforms and some people aren't super familiar with building the image themselves. It would be nice not to be forced to download the code and build it all yourself, when you simply need to use the application. 

Is there some reason that you are hesitant to do this, since it can be pretty easily automated?

**Comment by ahmetb** [comment]
> Is there some reason that you are hesitant to do this, since it can be pretty easily automated?

This unnecessarily increases the maintenance surface. It's also somewhat equivalent to asking for a docker image for every software you use. After all, it's just a single binary you can download and run. Given we can add more cross-platform binaries that matches the developer’s platform, I still don't know why we’d need a container image.

Can you please illustrate how you'd run this in a container image on a macOS or Windows dev machine and health-check a service that's not running in a container? My argument is that this tool is meant to be invoked over loopback interface (localhost), so running it as a separate container is not really a use case that's worth supporting.

**Comment by spkane** [comment]
On my Mac I have various scripts which need to run something like this at the end to confirm that things are running as expected.

`grpc_health_probe -tls -addr=app-demo.example.com:443`

With a native app, I can just use that, however today. I end up doing something like this:

```
alias grpc_health_probe="docker run --entrypoint=/usr/local/bin/grpc_health_probe stefanprodan/grpc_health_probe:v0.3.0 ${@}"
grpc_health_probe -tls -addr=app-demo.example.com:443
```

**Comment by ahmetb** [comment]
Yeah that's understandable, and a macOS build solves that? So there's no need for a container image?

**Comment by luca-esse** [comment]
Hello,
In my team we have the same scenario as OP, it would be very useful to have an official image without having to resort to building our own custom one.
Here's also another use case for Kubernetes: Injecting the probe with an initContainer.
Example:
`spec:
  volumes:
  - name: probe-vol
    emptyDir: {}
  initContainers:
  - name: probe
    image: grpc-health-probe:1.0.0
    command: ['sh', '-c', "cp /bin/grpc_health_probe /bin/probe/grpc_health_probe"]
    volumes:
      name: probe-vol
      mountPath: /bin/probe
  containers:
  - name: server
    image: "[YOUR-DOCKER-IMAGE]"
    ports:
    - containerPort: 5000
    readinessProbe:
      exec:
        command: ["/bin/probe/grpc_health_probe", "-addr=:5000"]
      initialDelaySeconds: 5
    livenessProbe:
      exec:
        command: ["/bin/probe/grpc_health_probe", "-addr=:5000"]
      initialDelaySeconds: 10
    volumes:
      name: probe-vol
      mountPath: /bin/probe
`
This solution could really help in a large microservices based project since you won't have to duplicate and mantain the probe installation in every microservice image.

**Comment by ahmetb** [comment]
@luca-esse That's a novel binary drop-in/delivery method I have not seen before, it's clever. The downside of such a method is that it reduces the reproducibility of the container by mutating its fs in the runtime. While it's not a great practice, as you said, it can help in a large-fleet without modifying the main container image.

That said, for uptime and availability, isn't it better if you mirror the image anyway, e.g. don't rely on GHCR.io or Docker Hub while deploying your images? In that case, mirroring the image is pretty much the same burden as having a 2-line dockerfile that does `ADD URL /bin/foo` `RUN chmod +x /foo` where you download this binary into a container image?

I get the point of requesting this, but providing a Docker image will open a larger can of worms as it also has its own cross-platform support for different architectures. And again, this request could also apply to potentially many other tools (say, curl), but since the existing delivery methods (binary distribution) also get you there with the same level of effort, I'm currently -1 on Container Image. But I'm ok with more cross-platform binaries.

**Comment by luca-esse** [comment]
Hi, I agree with you with the uptime and availabilities issues but there are ways around it.
I'm generally a fan of the image approach and I would like to point out that an official [(curl image)](https://hub.docker.com/r/curlimages/curl) actually exists and it has > 1billion downloads, in fact I use it really often when I have to debug something on Kubernetes really quick (the same use case could also apply to this tool, you could use it with a quick `kubectl run --image=grpc-health-probe [...]` for debugging purposes).

Ofc I could build the image myself and that's what I'm currently doing it but seeing that a few folks also requested it maybe an official image could save all of us some time and we would enjoy the tool better 🙂

**Comment by ahmetb** [comment]
@luca-esse @spkane If I provide a container image for this, it will be:
- a single binary in an image
- with the entrypoint set
- no other file (including CA roots)
- probably only linux/amd64 arch for the time being
- currently unsigned image but it’ll be probably signed with `cosign` down the line

does this sound good?

**Comment by spkane** [comment]
I'd personally add the root certs with a line like the one below, as I assume that it needs them in most circumstances.:

```dockerfile
COPY --from=0 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
```

But otherwise, that seems like a pretty reasonable place to start.

**Comment by ahmetb** [comment]
@spkane we wouldn't be writing a dockerfile to build the images + adding CA certs and keeping them  up to date is additional maintenance (e.g. say, we don't make a release for 2 years, that CA bundle will go stale). I don't see a clean way of handling this while providing one image per tag.

**Comment by luca-esse** [comment]
Sounds good to me 😀

**Comment by spkane** [comment]
That works for me as well. A few more native baniers and a Linux amd64 binary only container will be helpful. Thank you @ahmetb
