### ISSUE TITLE
environment variables expansion of args?

### ISSUE THREAD

**Issue by amrmahdi** [grpc-ecosystem/grpc-health-probe#97]
Currently the `exec` probes in kubernetes that does not support using environment variables in the exec command. See https://github.com/kubernetes/kubernetes/issues/40846. So there is no way to use environment variables referenced in the container spec, or that are built in into the container image.

The current work around is to use a shell e.g.  `bash -c <command>` which is not feasible in containers that do not have a shell, like distroless containers. 

My proposal is to do an environment variable expansion of the args that are parsed by the probe. 

Thought? If you agree with the general idea, we can discuss how it can be implemented.

**Comment by ahmetb** [comment]
I'd be -1 for environment variable interpolation and similar shell lexing features as they give the sense of completeness and parity with an actual shell and they are close to impossible to implement correctly.

(Aside: You can also make the same argument for practically any other tool as well, and each tool shouldn't have to think about interpolating shell variables. This sounds like a kubernetes shortcoming, indeed.)

My recommendation would be to use a sh -c "..." as well. 

I'd love to hear some concrete use cases, perhaps there's a way to help out differently.

**Comment by jzelinskie** [comment]
What are some of the corner cases that `os.ExpandEnv` doesn't handle?
I've typically used this in programs that I've written and would love to learn more to know if I should be more reserved about its use.

**Comment by ahmetb** [comment]
@jzelinskie I think `os.ExpandEnv` is an option, though, it also needs documenting, and people may try to do more sophisticated [parameter expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html)s that silently won't work.

Also there didn't seem to be enough users who needed this since this project is many years old and it only came up once.

I'm still interested in knowing what CLI arguments can use parameter expansion. At this point, Kubernetes has a native feature supporting gRPC health probes, and it's supposed to largely replace this tool (and I don't think it offers any such parameter expansions either).
